# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  clean:
    desc: cleans outputs
    cmds:
      - rm -rf output/player1/*
      - rm -rf output/player2/*
      - rm -rf output/player1grid/*
    silent: true
  run:
    desc: runs the application
    cmds:
      - go run .
    silent: true
